[book]
authors = ["Pistonight"]
language = "en"
src = "src"
title = "____CHANGE ME____"

#@mono-dev:preprocessor {
#@mono-dev:}

#@mono-dev:html {
[output.html]

# add extra props here

#@mono-dev:    props {}

additional-css = [
#@mono-dev:    css {}
]

#@mono-dev:}
