name: mono-dev pistonstor
description: Setup Pistonite Storage

runs:
  using: composite
  steps:
    - id: gcloud_auth
      uses: google-github-actions/auth@v2
      with:
        project_id: pistonstor
        workload_identity_provider: projects/262116032713/locations/global/workloadIdentityPools/github-actions/providers/github-provider
    - uses: google-github-actions/setup-gcloud@v2
