version: "3"

includes:
  mdbook:
    taskfile: ./task/mdbook.yaml
    internal: true

tasks:
  pull-book-update:
    desc: Update the book assets using newer mdbook version
    cmds:
      # can comment this out for efficiency,
      # but --force is needed so mdbook-admonish is built with latest mdbook
      - cargo install mdbook mdbook-admonish --force 
      - bun mdbook/update.ts

  install-deps:
    cmds:
      - task: mdbook:install-theme
        vars:
          MDBOOK_TARGET: website
          MONO_DEV: .

  dev-website:
    cmds:
      - task: build-website
      - mdbook watch website &
      - live-server website/book -p 8081

  build-website:
    desc: (Re-)build the book
    cmds:
      - rm -rf website/book
      - mdbook build website

  check:
    cmds:
      - node src/monolint.js

  fix:
    cmds:
      - node src/monolint.js --fix

  git-push:
    cmds:
      - git remote set-url origin git@github.com:Pistonight/mono-dev
      - git push
