version: "3"

includes:
  mdbook:
    taskfile: ./task/mdbook.yaml
    internal: true

tasks:
  install:
    desc: Install or sync project dependencies
    cmds:
      - pnpm install
      - task: copy-website-theme

        # blocker: mdbook-admonish does not support mdbook 0.5
  # pull-book-update:
  #   desc: Update the book assets using newer mdbook version
  #   cmds:
  #     # can comment this out for efficiency,
  #     # but --force is needed so mdbook-admonish is built with latest mdbook
  #     - cargo install mdbook mdbook-admonish --force 
  #     - bun toolsets/mdbook/update.ts

  copy-website-theme:
    desc: Copy mdbook themes from the toolset to the website
    cmds:
      - task: mdbook:install-theme
        vars:
          MDBOOK_TARGET: website

  build:
    desc: Build with bootstrap
    cmds:
      - rm -rf dist
      - bun scripts/bootstrap-stage1.ts
      - pnpm exec vite build
      - cmd: "echo 'bootstrap: re-running vite build with mono'"
        silent: true
      - node bin/mono.js build
      - node bin/mono.js config

  check:
    desc: Check style
    deps: [build]
    cmds:
      - node bin/mono.js check
  fix:
    desc: Fix style
    deps: [build]
    cmds:
      - node bin/mono.js check -f

  test:
    deps: [build]
    cmds:
      - node bin/mono.js test run
      - node bin/mono.js doc

  dev:
    cmds:
      - rm -rf website/book
      - shwoop website/book -w website --host -- mdbook build website

  build-website:
    desc: (Re-)build the book
    cmds:
      - rm -rf website/book
      - mdbook build website

  package:
    desc: Package the package using publish --dry-run
    cmds:
      - node bin/mono.js publish --dry-run

  publish:
    desc: Publish to the dist branch
    vars:
      VERSION:
        sh: jq '.version' package.json | tr -d '"'
    cmds:
      - node bin/mono.js check
      - node bin/mono.js test run
      - node bin/mono.js publish --dry-run
      - silent: true
        cmd: >
             rm -rf node_modules/.mono/publish;
             mkdir -p node_modules/.mono/publish;
             git -C node_modules/.mono/publish init;
             git -C node_modules/.mono/publish remote add origin git@github.com:Pistonight/mono-dev;
             git -C node_modules/.mono/publish fetch origin dist;
             git -C node_modules/.mono/publish checkout dist;
             lastversion=$(jq '.version' node_modules/.mono/publish/package.json | tr -d '"');
             nextversion="{{.VERSION}}";
             if [ "$lastversion" = "$nextversion" ]; then
               echo "version $nextversion is already published";
               exit 2;
             fi;
             cp -R node_modules/.mono/pnpm-pack.temp/package/* node_modules/.mono/publish;
             git -C node_modules/.mono/publish add .;
             git -C node_modules/.mono/publish commit -m "publish: $nextversion";
             git -C node_modules/.mono/publish push;
             echo "published $lastversion -> $nextversion";

    

  upgrade:
    desc: Upgrade dependencies
    cmds:
      - pnpm install @typescript/native-preview@beta
      - >-
        pnpm up
        @types/bun @types/node
        vite @babel/core @rolldown/plugin-babel @types/babel__core babel-plugin-react-compiler
        @vitejs/plugin-react
        vite-plugin-wasm
        @eslint/js eslint eslint-plugin-react-hooks eslint-plugin-react-refresh eslint-plugin-react-compiler
        globals
        typescript
        typescript-eslint
        js-yaml
        vitest
        typedoc typedoc-theme-oxide
        which @types/which
      - pnpm dedupe
      - pnpm dedupe --check
