version: "3"

includes:
  mdbook:
    taskfile: ./task/mdbook.yaml
    internal: true

tasks:
  install:
    cmds:
      - pnpm install
      - task: install-deps

        # blocker: mdbook-admonish does not support mdbook 0.5
  # pull-book-update:
  #   desc: Update the book assets using newer mdbook version
  #   cmds:
  #     # can comment this out for efficiency,
  #     # but --force is needed so mdbook-admonish is built with latest mdbook
  #     - cargo install mdbook mdbook-admonish --force 
  #     - bun toolsets/mdbook/update.ts

  install-deps:
    cmds:
      - task: mdbook:install-theme
        vars:
          MDBOOK_TARGET: website
          MONO_DEV: .

  dev:
    cmds:
      - task: build-website
      - mdbook watch website &
      - live-server website/book -p 8081

  build-website:
    desc: (Re-)build the book
    cmds:
      - rm -rf website/book
      - mdbook build website

  git-push:
    cmds:
      - git remote set-url origin git@github.com:Pistonight/mono-dev
      - git push

  publish:
    vars:
      VERSION:
        sh: jq '.version' package.json | tr -d '"'
    cmds:
      - git tag v{{.VERSION}}
      - git push origin v{{.VERSION}}

  upgrade:
    - >-
      pnpm up
      @types/bun @types/node
      vite @babel/core @rolldown/plugin-babel @types/babel__core babel-plugin-react-compiler
      react react-dom @types/react @types/react-dom
      @vitejs/plugin-react
      vite-plugin-wasm
      @modyfi/vite-plugin-yaml
      @eslint/js eslint eslint-plugin-react-hooks eslint-plugin-react-refresh eslint-plugin-react-compiler
      globals
      typescript
      typescript-eslint
      js-yaml
      vitest
      typedoc typedoc-theme-oxide
    - pnpm dedupe
    - pnpm dedupe --check
