name: mono-dev docker
description: Build and Publish a Docker image to GHCR

inputs:
  artifacts-workflow:
    description: "Workflow name to download artifacts from"
    default: ""
  artifacts-path:
    description: "Path to download artifacts to"
    default: ""
  task:
    description: "Task to run after downloading artifacts"
    default: ""
  image:
    description: "Docker image name (without registry prefix)"
    required: true
  version:
    description: "Version tag"
    required: true
  path:
    description: "Path to directory containing Dockerfile"
    required: true

runs:
  using: composite
  steps:
    - if: ${{ inputs.artifacts-workflow != '' && inputs.artifacts-path != '' }}
      run: mkdir -p ${{ inputs.artifacts-path }}
      shell: bash
    - if: ${{ inputs.artifacts-workflow != '' && inputs.artifacts-path != '' }}
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{ github.token }}
        workflow: ${{ inputs.artifacts-workflow }}
        commit: ${{ github.sha }}
        path: ${{ inputs.artifacts-path }}

    - if: ${{ inputs.task != '' }}
      run: task exec -- ${{ inputs.task }}
      shell: bash

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ghcr.io/${{ inputs.image }}
        tags: |
          type=sha
          type=sha,format=long
          type=raw,value=${{ inputs.version }}
          type=raw,value=latest
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: ${{ inputs.path }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
