import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import reactCompiler from "eslint-plugin-react-compiler";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";



/** @type {import("eslint").ESLint.Plugin} */
const localPlugin = {
    rules: {
        "no-keyof-typeof-alias": {
            meta: {
                type: "suggestion",
                messages: {
                    noKeyofTypeofAlias: "Avoid exporting type aliases of the form 'keyof typeof X'. Inline the type so it shows up in the documentation more precisely.",
                },
            },
            /** @param {import("eslint").Rule.RuleContext} context */
            create(context) {
                return {
                    /** @param {any} node */
                    "ExportNamedDeclaration > TSTypeAliasDeclaration"(node) {
                        const t = node.typeAnnotation;
                        if (t.type === "TSTypeOperator" && t.operator === "keyof" && t.typeAnnotation?.type === "TSTypeQuery") {
                            context.report({ node, messageId: "noKeyofTypeofAlias" });
                        }
                    },
                };
            },
        },
        "no-param-destructure": {
            meta: {
                type: "suggestion",
                messages: {
                    noParamDestructure: "Avoid object destructuring in function parameters in library code. Use a named parameter to ensure it is presented properly in generated documentation.",
                },
            },
            /** @param {import("eslint").Rule.RuleContext} context */
            create(context) {
                /** @param {any} node */
                function checkParams(node) {
                    for (const param of node.params) {
                        if (param.type === "ObjectPattern") {
                            context.report({ node: param, messageId: "noParamDestructure" });
                        }
                    }
                }
                return {
                    "ExportNamedDeclaration > FunctionDeclaration": checkParams,
                    "ExportDefaultDeclaration > FunctionDeclaration": checkParams,
                    "ExportDefaultDeclaration > FunctionExpression": checkParams,
                    "ExportNamedDeclaration > VariableDeclaration > VariableDeclarator > ArrowFunctionExpression": checkParams,
                    "ExportDefaultDeclaration > ArrowFunctionExpression": checkParams,
                };
            },
        },
    },
};

/** @param {import("./eslint_config.js").Config} configObj */
export function config(configObj) {
    const enableReact = configObj.react ?? true;
    const config = defineConfig(
        globalIgnores(configObj.ignores || []),
        {
            extends: [
                js.configs.recommended,
                ...tseslint.configs.strict,
                ...(enableReact
                    ? [
                        reactHooks.configs.flat.recommended,
                        reactRefresh.configs.vite,
                        reactCompiler.configs.recommended
                    ]
                    : []),
            ],
            files: ["**/*.{ts,mts,cts,tsx}"],
            languageOptions: {
                ecmaVersion: 2020,
                globals: globals.browser,
                parserOptions: {
                    projectService: true,
                    tsconfigRootDir: configObj.tsconfigRootDir || undefined,
                },
            },
            settings: {
                ...(enableReact
                    ? {
                          react: { version: "19" },
                      }
                    : {}),
            },
            plugins: {
                ...(configObj.isLib ? { "monodev-eslint": localPlugin } : {}),
            },
            rules: {
                ...(enableReact
                    ? {
                          "react-refresh/only-export-components": [
                              "warn",
                              { allowConstantExport: true },
                          ],
                      }
                    : {}),
                "no-unused-vars": "off",
                // force type to be import as type
                "@typescript-eslint/consistent-type-imports": "warn",
                // force you to mark floating promises with `void` (warning for ease with testing)
                "@typescript-eslint/no-floating-promises": "warn",
                ...(configObj.isLib ? {
                    // when writing library, use interface when possible gives better presentation
                    // in the documentation generated by typedoc
                    "@typescript-eslint/consistent-type-definitions": ["warn", "interface"],
                    // avoid object destructuring in function params for clearer library APIs
                    "monodev-eslint/no-param-destructure": "warn",
                    // avoid exporting keyof typeof aliases as they produce poor typedoc output
                    "monodev-eslint/no-keyof-typeof-alias": "warn",
                } : undefined),
            },
        },
    );

    return override(config, getDefaultOverrides(configObj));
}

/** @param {import("./eslint_config.js").Config} configObj */
const getDefaultOverrides = (configObj) => {
    // these only apply if they are already in the config
    // otherwise add it to above
    return {
        // typescript has coverage already
        "@typescript-eslint/no-unused-vars": [
            "warn",
            { varsIgnorePattern: "^_", argsIgnorePattern: "^_" },
        ],
        "@typescript-eslint/restrict-template-expressions": ["warn", { allowNumber: true }],
        // we have TypeScript
        "react/prop-types": "off",
    };
};

export function override(configs, overrides) {
    if (Array.isArray(configs)) {
        for (const config of configs) {
            override(config, overrides);
        }
    } else {
        if (configs.rules) {
            for (const rule in overrides) {
                if (configs.rules[rule]) {
                    configs.rules[rule] = overrides[rule];
                }
            }
        }
    }
    return configs;
}
