[package]
name = "mono-dev-mdbook-preproc"
version = "0.0.0"
description = "all-in-one tool and preprocessor for mdbook"
edition = "2024"

[dependencies]
cu = { workspace = true, features = ["cli", "toml", "process", "derive"] }
similar.workspace = true

[[bin]]
name = "mdmdbook-prproc"
path = "src/main.rs"
