import path from "node:path";
import fs from "node:fs";

import type { Linter } from "eslint";
import { defineConfig, globalIgnores } from "eslint/config";
import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import reactCompiler from "eslint-plugin-react-compiler";
import tseslint from "typescript-eslint";

import { MonodevEslintPlugin } from "#plugins";
import { getProjectPackageJsonPath, hasDependency, type PackageJson } from "#util";
import { getIgnoreConfig } from "#project";

export const configure = () => {
    const packageJsonPath = getProjectPackageJsonPath();
    const rootDir = path.dirname(packageJsonPath);
    const packageJson: PackageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8"));
    const enableReact = hasDependency(packageJson, "react");
    const monodevOptions = packageJson["pistonight/mono-dev"] || {};
    const isLib = !(monodevOptions.lib === false);

    const config = defineConfig(globalIgnores(findIgnores(packageJson, rootDir)), {
        extends: [
            js.configs.recommended,
            ...tseslint.configs.strict,
            ...(enableReact
                ? [
                      reactHooks.configs.flat.recommended,
                      reactRefresh.configs.vite,
                      reactCompiler.configs.recommended,
                  ]
                : []),
        ],
        files: ["**/*.{ts,mts,cts,tsx}"],
        languageOptions: {
            ecmaVersion: 2020,
            globals: globals.browser,
            parserOptions: {
                projectService: true,
                tsconfigRootDir: rootDir,
            },
        },
        settings: {
            ...(enableReact
                ? {
                      react: { version: "19" },
                  }
                : {}),
        },
        plugins: {
            ...(isLib ? { "monodev-eslint": MonodevEslintPlugin } : {}),
        },
        rules: {
            ...(enableReact
                ? {
                      "react-refresh/only-export-components": [
                          "warn",
                          { allowConstantExport: true },
                      ],
                  }
                : {}),
            "no-unused-vars": "off",
            // force type to be import as type
            "@typescript-eslint/consistent-type-imports": "warn",
            // force you to mark floating promises with `void` (warning for ease with testing)
            "@typescript-eslint/no-floating-promises": "warn",
            ...(isLib
                ? {
                      // when writing library, use interface when possible gives better presentation
                      // in the documentation generated by typedoc
                      "@typescript-eslint/consistent-type-definitions": ["warn", "interface"],
                      // avoid object destructuring in function params for clearer library APIs
                      "monodev-eslint/no-param-destructure": "warn",
                      // avoid exporting keyof typeof aliases as they produce poor typedoc output
                      "monodev-eslint/no-keyof-typeof-alias": "warn",
                  }
                : undefined),
        },
    });

    return overrideEslintConfig(config, getDefaultOverrides());
};

const getDefaultOverrides = (): Linter.RulesRecord => {
    // these only apply if they are already in the config
    // otherwise add it to above
    return {
        // typescript has coverage already
        "@typescript-eslint/no-unused-vars": [
            "warn",
            { varsIgnorePattern: "^_", argsIgnorePattern: "^_" },
        ],
        "@typescript-eslint/restrict-template-expressions": ["warn", { allowNumber: true }],
        // we have TypeScript
        "react/prop-types": "off",
    };
};

export const overrideEslintConfig = <T extends keyof EslintConfigPartSelector>(
    configs: EslintConfigPartSelector[T],
    overrides: Linter.RulesRecord,
): EslintConfigPartSelector[T] => {
    if (Array.isArray(configs)) {
        for (const config of configs) {
            overrideEslintConfig(config, overrides);
        }
    } else {
        if (configs.rules) {
            for (const rule in overrides) {
                if (configs.rules[rule]) {
                    configs.rules[rule] = overrides[rule];
                }
            }
        }
    }
    return configs;
};

export interface EslintConfigPart {
    rules?: Partial<Linter.RulesRecord> | undefined;
}
export interface EslintConfigPartSelector {
    single: EslintConfigPart;
    array: EslintConfigPart[];
}

const findIgnores = (packageJson: PackageJson, rootDir: string): string[] => {
    //ignore the config itself
    const ignores: string[] = ["./eslint.config.js"];

    // ignore non-ts directories
    for (const p of fs.readdirSync(rootDir)) {
        try {
            if (fs.statSync(`${rootDir}/${p}`).isDirectory()) {
                try {
                    fs.statSync(`${rootDir}/${p}/env.d.ts`);
                } catch {
                    ignores.push("./" + p);
                }
            }
        } catch {
            // ignore
        }
    }
    const ignoreConfig = getIgnoreConfig(packageJson, rootDir);
    for (const line of ignoreConfig) {
        if (line.includes("tsconfig") || line.includes("eslint.config.js")) {
            continue;
        }
        if (line.startsWith("!")) {
            continue;
        }
        if (line.startsWith("/")) {
            ignores.push(`.${line}`);
        } else {
            ignores.push(`**/${line}`);
        }
    }
    return ignores;
};
