[book]
authors = ["Pistonight"]
language = "en"
src = "src"
title = "mono-dev"

[output.html]
default-theme = "frappe"
preferred-dark-theme = "frappe"
smart-punctuation = true
git-repository-url = "https://github.com/Pistonight/mono-dev"
additional-css = [
    "./theme/extra-css/catppuccin.css", 
    "./theme/extra-css/patch.css", 
]
